package pl.aridlin.psychiatrykroles;
import net.neoforged.fml.common.Mod;
import net.neoforged.neoforge.common.NeoForge;
import net.neoforged.neoforge.event.tick.ServerTickEvent;
import net.minecraft.core.*;
import net.minecraft.nbt.*;
import net.minecraft.world.phys.*;
import net.minecraft.world.level.block.*;
import net.minecraft.world.level.block.state.properties.*;
import java.util.*;
@Mod("goplanska_unified_check")
public class UnifiedCheck {
 int ticks;public UnifiedCheck(){NeoForge.EVENT_BUS.addListener(this::tick);}
 void check(boolean b,String message){if(!b)throw new AssertionError(message);}
 void tick(ServerTickEvent.Post e){if(++ticks!=40)return;try{
 var server=e.getServer();var level=server.overworld();var pos=new BlockPos(10,100,10);
 var d=VoidExitDirections.get(server);if(d.flipped(level,pos))d.toggle(level,pos);check(d.toggle(level,pos),"first toggle");check(VoidExitDirections.exit(level,pos,Direction.NORTH)==Direction.SOUTH,"180 exit");
 var restored=VoidExitDirections.load(d.save(new CompoundTag(),server.registryAccess()),server.registryAccess());check(restored.flipped(level,pos),"persistent exit setting");
 var a=ImmersiveVoidPortals.door(level,pos,Direction.NORTH);check(!d.toggle(level,pos),"second toggle");var b=ImmersiveVoidPortals.door(level,pos,Direction.NORTH);check(a.center().equals(b.center())&&a.widthAxis().distanceToSqr(b.widthAxis().scale(-1))<1e-12,"immersive plane stays in frame and reverses orientation");
 var player=net.neoforged.neoforge.common.util.FakePlayerFactory.get(level,new com.mojang.authlib.GameProfile(UUID.randomUUID(),"DoorCheck"));
 var pair=UUID.randomUUID();var state=Blocks.DARK_OAK_DOOR.defaultBlockState().setValue(DoorBlock.HALF,DoubleBlockHalf.LOWER);level.setBlock(pos,state,3);level.setBlock(pos.above(),state.setValue(DoorBlock.HALF,DoubleBlockHalf.UPPER),3);VoidDoorData.get(server).addDoor(pair,new VoidDoorData.DoorPosition(level.dimension().location().toString(),pos));
 player.setShiftKeyDown(true);player.setItemInHand(net.minecraft.world.InteractionHand.MAIN_HAND,new net.minecraft.world.item.ItemStack(net.minecraft.world.item.Items.IRON_HOE));
 var use=new net.neoforged.neoforge.event.entity.player.PlayerInteractEvent.RightClickBlock(player,net.minecraft.world.InteractionHand.MAIN_HAND,pos,new BlockHitResult(Vec3.atCenterOf(pos),Direction.NORTH,pos,false));new VoidDoors().onDoorUse(use);check(use.isCanceled()&&d.flipped(level,pos),"shift hoe click reverses exit");check(level.getBlockState(pos).equals(state),"door geometry unchanged");
 var trapdoors=new VoidTrapdoors();var guardClass=Class.forName("pl.aridlin.psychiatrykroles.VoidTrapdoors$ExitGuard");var constructor=guardClass.getDeclaredConstructors()[0];constructor.setAccessible(true);var guards=VoidTrapdoors.class.getDeclaredField("exitGuards");guards.setAccessible(true);var map=(Map)guards.get(trapdoors);map.put(player.getUUID(),constructor.newInstance(level.dimension().location().toString(),pos,100));var method=VoidTrapdoors.class.getDeclaredMethod("guarded",net.minecraft.world.entity.Entity.class,int.class);method.setAccessible(true);
 player.setPos(10.5,101,10.5);check((Boolean)method.invoke(trapdoors,player,99),"cooldown blocks reentry");check((Boolean)method.invoke(trapdoors,player,120),"standing above exit still blocks loop");player.setPos(14,101,14);check(!(Boolean)method.invoke(trapdoors,player,120)&&map.isEmpty(),"leave exit re-enables deliberate return");
 check(level.getGameRules().getInt(net.minecraft.world.level.GameRules.RULE_PLAYERS_SLEEPING_PERCENTAGE)==50,"50 percent survives roles tick");
 for(String kind:new String[]{"door","immersive_door","trapdoor","immersive_trapdoor"}){var stack=VoidGive.pair(kind,true);check(stack.getCount()==2,"pair quantity");check(kind.endsWith("trapdoor")?VoidTrapdoors.pair(stack)!=null:VoidDoors.pair(stack)!=null,"unique linked give output");}
 var areaData=new MarkAreaData();var owner=UUID.randomUUID();var first=areaData.place(owner,"minecraft:overworld",new BlockPos(0,100,0));check(first.b()==null,"first area corner");var area=areaData.place(owner,"minecraft:overworld",new BlockPos(10,104,12));check(area.id().equals(first.id())&&area.b()!=null,"second torch completes area");var copy=MarkAreaData.load(areaData.save(new CompoundTag(),server.registryAccess()),server.registryAccess());check(copy.areas.equals(areaData.areas),"area persistence");copy.remove("minecraft:overworld",area.b());check(copy.areas.isEmpty(),"breaking either corner removes area");
 var ingredients=net.minecraft.world.item.crafting.CraftingInput.of(1,2,List.of(new net.minecraft.world.item.ItemStack(net.minecraft.world.item.Items.GLOWSTONE_DUST),new net.minecraft.world.item.ItemStack(net.minecraft.world.item.Items.STICK)));var recipe=server.getRecipeManager().getRecipeFor(net.minecraft.world.item.crafting.RecipeType.CRAFTING,ingredients,level);check(recipe.isPresent(),"marking torch recipe exists");var output=recipe.get().value().assemble(ingredients,level.registryAccess());check(output.is(MarkingTorches.ITEM)&&output.getCount()==2,"glowstone + stick makes two marking torches");
 var lens=LootLens.ITEM;check(lens!=null,"loot lens registered");
 var lensInput=net.minecraft.world.item.crafting.CraftingInput.of(3,1,List.of(new net.minecraft.world.item.ItemStack(net.minecraft.world.item.Items.SPYGLASS),new net.minecraft.world.item.ItemStack(net.minecraft.world.item.Items.GLOWSTONE_DUST),new net.minecraft.world.item.ItemStack(net.minecraft.world.item.Items.GOLD_INGOT)));
 var lensRecipe=server.getRecipeManager().getRecipeFor(net.minecraft.world.item.crafting.RecipeType.CRAFTING,lensInput,level);check(lensRecipe.isPresent()&&lensRecipe.get().value().assemble(lensInput,level.registryAccess()).is(lens),"lens crafting recipe");
 var cap=io.wispforest.accessories.api.AccessoriesCapability.get(player);check(cap!=null,"accessories capability available");var face=cap.getContainers().get("face");check(face!=null,"face slot available");var lensStack=new net.minecraft.world.item.ItemStack(lens);check(io.wispforest.accessories.api.AccessoriesAPI.canEquip(lensStack,face.createReference(0)),"lens fits face slot");
 player.setShiftKeyDown(false);check(!LootLens.active(player),"inactive without crouch/equip");face.getAccessories().setItem(0,lensStack);check(!LootLens.active(player),"equipped lens inactive standing");player.setShiftKeyDown(true);check(LootLens.active(player),"equipped crouching lens active");face.getAccessories().setItem(0,net.minecraft.world.item.ItemStack.EMPTY);check(!LootLens.active(player),"unequipping disables lens");
 for(var extra:net.minecraft.world.item.Rarity.values()){var extraStack=new net.minecraft.world.item.ItemStack(net.minecraft.world.item.Items.STICK);extraStack.set(net.minecraft.core.component.DataComponents.RARITY,extra);check((LootLens.color(extraStack)&0xff000000)==0xff000000,"modded rarity supported");}
 int[] colors={0xffffffff,0xffffff55,0xff55ffff,0xffff55ff};int ci=0;for(var rarity:new net.minecraft.world.item.Rarity[]{net.minecraft.world.item.Rarity.COMMON,net.minecraft.world.item.Rarity.UNCOMMON,net.minecraft.world.item.Rarity.RARE,net.minecraft.world.item.Rarity.EPIC}){var stack=new net.minecraft.world.item.ItemStack(net.minecraft.world.item.Items.STICK);stack.set(net.minecraft.core.component.DataComponents.RARITY,rarity);check(LootLens.color(stack)==colors[ci++],"rarity color "+rarity);}
 var packet=new MarkSync(List.of(new MarkSync.Mark(owner,0,1,2,3,4,5,0xffffdd55,false)));var buf=new net.minecraft.network.RegistryFriendlyByteBuf(io.netty.buffer.Unpooled.buffer(),server.registryAccess());MarkSync.CODEC.encode(buf,packet);check(MarkSync.CODEC.decode(buf).equals(packet),"mark packet roundtrip");buf.release();
 var presets=PsychiatrykRoles.class.getDeclaredField("ITEM_PRESETS");presets.setAccessible(true);check(((List<?>)presets.get(null)).containsAll(CustomPresets.EXTRA),"all extras in preset suggestions/list");var maker=PsychiatrykRoles.class.getDeclaredMethod("presetItem",String.class,net.minecraft.server.level.ServerPlayer.class,long.class);maker.setAccessible(true);for(var preset:CustomPresets.EXTRA){var result=(net.minecraft.world.item.ItemStack)maker.invoke(null,preset,player,0L);check(!result.isEmpty(),"preset produces item: "+preset);if(preset.contains("void-"))check(result.getCount()==2,"door preset gives linked pair");}check(!((net.minecraft.world.item.ItemStack)maker.invoke(null,"return-mirror",player,0L)).isEmpty(),"old presets still work");long expiry=System.currentTimeMillis()+60000;var timed=(net.minecraft.world.item.ItemStack)maker.invoke(null,"loot-lens",player,expiry);check(ItemTagCompat.read(timed).getLong("psychiatrykConsultantExpiresAt")==expiry,"timed new preset preserves expiry");check(pl.aridlin.parties.CoverThickness.between(level,new Vec3(0,100,0),new Vec3(1000,100,0))==16,"distant dots skip expensive portal raycast");
 var boost=VoidTrapdoors.popVelocity(Direction.NORTH);check(boost.y>=.42&&boost.z<=-.35,"jump and outward boost");
 check(server.getCommands().getDispatcher().getRoot().getChild("voidgive")!=null&&server.getCommands().getDispatcher().getRoot().getChild("spectate")!=null&&server.getCommands().getDispatcher().getRoot().getChild("party")!=null,"merged commands registered");check(net.neoforged.fml.ModList.get().isLoaded("goplanska_starter")&&net.neoforged.fml.ModList.get().isLoaded("goplanska_kukirin")&&net.neoforged.fml.ModList.get().isLoaded("goplanska_party_markers"),"all merged modules loaded");
 System.out.println("UNIFIED_CHECK PASS door toggle + saved settings + fixed immersive frame + jump boost + loop guard + merged modules/commands + marking torch recipe, pair persistence, erase, packet + Loot Lens recipe, face equip, crouch gate and all rarity colors + all 12 new presets, existing fallback and timed expiry");
 }catch(Throwable t){t.printStackTrace();System.out.println("UNIFIED_CHECK FAIL "+t);}e.getServer().halt(false);}
}
