package pl.aridlin.kukirin;
import java.util.*;import java.util.concurrent.atomic.*;import java.lang.reflect.*;
import io.netty.buffer.Unpooled;import net.minecraft.network.RegistryFriendlyByteBuf;import net.minecraft.core.RegistryAccess;import net.minecraft.core.BlockPos;
public class PauseCodecCheck {
 static int checks;static void check(boolean ok,String why){checks++;if(!ok)throw new AssertionError(why);}
 static RegistryFriendlyByteBuf buf(){return new RegistryFriendlyByteBuf(Unpooled.buffer(),RegistryAccess.EMPTY);}
 public static void main(String[] args)throws Exception{
  AtomicLong nanos=new AtomicLong(5000000000L);MusicSessionClock clock=new MusicSessionClock(nanos::get);nanos.addAndGet(1234567000L);check(clock.elapsedMillis()==1234,"server elapsed monotonic");check(clock.setPaused(true),"pause changes state");long frozen=clock.elapsedMillis();nanos.addAndGet(90_000_000_000L);check(clock.elapsedMillis()==frozen,"pause freezes playhead beyond song duration");check(!clock.setPaused(true),"repeated pause is idempotent");check(clock.setPaused(false),"resume changes state");check(clock.elapsedMillis()==frozen,"resume same position");nanos.addAndGet(250_000_000L);check(clock.elapsedMillis()==1484,"only unpaused time advances");clock.setPaused(true);nanos.addAndGet(999_000_000_000L);clock.setPaused(false);check(clock.elapsedMillis()==1484,"second pause preserves cumulative time");
  check(MusicTimeline.position(9876,0,100_000_000_000L,400,true,true)==9.876,"late listener pause does not extrapolate");check(MusicTimeline.position(9876,0,1_000_000_000L,400,true,false)==10.876,"resume snapshot extrapolates shared clock");
  for(boolean paused:new boolean[]{false,true})for(boolean loop:new boolean[]{false,true})for(long ms:new long[]{0,7,Long.MAX_VALUE}){
   var packet=new ScooterAudioUrlPacket(UUID.randomUUID(),UUID.randomUUID(),false,new BlockPos(1,2,3),"https://prol.aridlin.pl/scooter-audio/"+"a".repeat(64)+".wav","fixture","a".repeat(64),444,loop,ms,1200,88,paused);var b=buf();ScooterAudioUrlPacket.CODEC.encode(b,packet);check(ScooterAudioUrlPacket.CODEC.decode(b).equals(packet),"actual URL codec paused roundtrip");check(b.readableBytes()==0,"URL codec fully consumed");b.release();
   var catalog=new ScooterMusicMenu.Catalog(List.of("one.wav","two.wav"),true,false,loop,paused);b=buf();ScooterMusicMenu.Catalog.CODEC.encode(b,catalog);check(ScooterMusicMenu.Catalog.CODEC.decode(b).equals(catalog),"full catalog paused roundtrip");check(b.readableBytes()==0,"catalog fully consumed");b.release();
   var part=new ScooterMusicMenu.CatalogPart(UUID.randomUUID(),64,true,false,true,false,loop,paused,"two.wav",List.of("one.wav","two.wav"));b=buf();ScooterMusicMenu.CatalogPart.CODEC.encode(b,part);check(ScooterMusicMenu.CatalogPart.CODEC.decode(b).equals(part),"chunked catalog paused roundtrip");b.release();
   var options=new ScooterMusicMenu.Options(true,true,paused);b=buf();ScooterMusicMenu.Options.CODEC.encode(b,options);check(ScooterMusicMenu.Options.CODEC.decode(b).equals(options),"options authoritative paused state");b.release();
  }
  check(!new ScooterAudioUrlPacket(UUID.randomUUID(),UUID.randomUUID(),false,BlockPos.ZERO,"","","",0,false).paused(),"9arg URL binary-compatible constructor");check(!new ScooterAudioUrlPacket(UUID.randomUUID(),UUID.randomUUID(),false,BlockPos.ZERO,"","","",0,false,0,0,-1).paused(),"12arg URL constructor retained");check(!new ScooterMusicMenu.Catalog(List.of(),true,false,false).paused(),"old catalog ctor retained");check(!new ScooterMusicMenu.Options(false,false).paused(),"old options ctor retained");check(!new ScooterMusicMenu.CatalogPart(UUID.randomUUID(),0,true,false,true,false,false,List.of()).paused(),"old short part ctor retained");check(!new ScooterMusicMenu.CatalogPart(UUID.randomUUID(),0,true,false,true,false,false,"",List.of()).paused(),"old focus part ctor retained");
  for(int scenario=0;scenario<3;scenario++){boolean rejected=false;try{new ScooterAudioUrlPacket(UUID.randomUUID(),UUID.randomUUID(),false,BlockPos.ZERO,"","","",0,false,scenario==0?-1:0,scenario==1?-1:0,scenario==2?-2:0,true);}catch(IllegalArgumentException good){rejected=true;}check(rejected,"malformed timestamps rejected");}
  Field timelineField=ScooterAudioClient.class.getDeclaredField("timelines");timelineField.setAccessible(true);Map<UUID,Object> timelines=(Map<UUID,Object>)timelineField.get(null);Class<?> timeline=Class.forName("pl.aridlin.kukirin.ScooterAudioClient$Timeline");Constructor<?> ctor=timeline.getDeclaredConstructors()[0];ctor.setAccessible(true);Method allowed=ScooterAudioClient.class.getDeclaredMethod("audioAllowed",UUID.class,UUID.class);allowed.setAccessible(true);UUID source=UUID.randomUUID(),session=UUID.randomUUID();var pausedPacket=new ScooterAudioUrlPacket(source,session,false,BlockPos.ZERO,"","","",0,true,5000,1200,1,true);timelines.put(source,ctor.newInstance(pausedPacket,System.nanoTime()));check(!(boolean)allowed.invoke(null,source,session),"async stream gate blocks paused session");check(!(boolean)allowed.invoke(null,source,UUID.randomUUID()),"old session callback blocked");var resumed=new ScooterAudioUrlPacket(source,session,false,BlockPos.ZERO,"","","",0,true,5000,1200,1,false);timelines.put(source,ctor.newInstance(resumed,System.nanoTime()));check((boolean)allowed.invoke(null,source,session),"same session resumes gate");timelines.clear();
  for(int gain:new int[]{0,37,100}) {
   var packet=new ScooterAudioUrlPacket(source,session,false,BlockPos.ZERO,"","","",0,true,5000,1200,1,true,gain);var b=buf();ScooterAudioUrlPacket.CODEC.encode(b,packet);check(ScooterAudioUrlPacket.CODEC.decode(b).volume()==gain,"shared gain URL native codec");b.release();
   var catalog=new ScooterMusicMenu.Catalog(List.of("one.wav"),true,false,true,true,gain);b=buf();ScooterMusicMenu.Catalog.CODEC.encode(b,catalog);check(ScooterMusicMenu.Catalog.CODEC.decode(b).equals(catalog),"full catalog gain roundtrip");b.release();
   var part=new ScooterMusicMenu.CatalogPart(UUID.randomUUID(),0,true,false,true,false,true,true,gain,"",List.of("one.wav"));b=buf();ScooterMusicMenu.CatalogPart.CODEC.encode(b,part);check(ScooterMusicMenu.CatalogPart.CODEC.decode(b).equals(part),"chunk catalog gain roundtrip");b.release();
   var options=new ScooterMusicMenu.Options(true,true,true,gain);b=buf();ScooterMusicMenu.Options.CODEC.encode(b,options);check(ScooterMusicMenu.Options.CODEC.decode(b).equals(options),"options gain roundtrip");b.release();
   var unpaused=new ScooterAudioUrlPacket(source,session,false,BlockPos.ZERO,"","","",0,true,5000,1200,1,false,gain);timelines.put(source,ctor.newInstance(unpaused,System.nanoTime()));check((boolean)allowed.invoke(null,source,session)==(gain>0),"mute stops source without pausing clock");
  }
  for(int gain:new int[]{-1,101}) {boolean rejected=false;try{new ScooterAudioUrlPacket(source,session,false,BlockPos.ZERO,"","","",0,true,0,1,1,false,gain);}catch(IllegalArgumentException good){rejected=true;}check(rejected,"gain packet rejects out of range");}
  check(new ScooterMusicMenu.Options(false,false,true).volume()==100,"old paused options ctor retains default gain");
  var activeCatalog=new ScooterMusicMenu.Catalog(List.of("one.wav"),true,false,true,true,37,"one.wav");var activeBuffer=buf();ScooterMusicMenu.Catalog.CODEC.encode(activeBuffer,activeCatalog);check(ScooterMusicMenu.Catalog.CODEC.decode(activeBuffer).currentSong().equals("one.wav"),"authoritative now playing key in catalog");activeBuffer.release();
  var activeOptions=new ScooterMusicMenu.Options(true,false,true,37,"one.wav");activeBuffer=buf();ScooterMusicMenu.Options.CODEC.encode(activeBuffer,activeOptions);check(ScooterMusicMenu.Options.CODEC.decode(activeBuffer).currentSong().equals("one.wav"),"current song key in live options");activeBuffer.release();
  var activePart=new ScooterMusicMenu.CatalogPart(UUID.randomUUID(),0,true,false,true,false,true,true,37,"one.wav","",List.of("one.wav"));activeBuffer=buf();ScooterMusicMenu.CatalogPart.CODEC.encode(activeBuffer,activePart);check(ScooterMusicMenu.CatalogPart.CODEC.decode(activeBuffer).currentSong().equals("one.wav"),"chunked current key");activeBuffer.release();
  UUID physicalSource=UUID.randomUUID();var sourced=new ScooterMusicMenu.Catalog(List.of("one.wav"),true,false,true,true,37,"one.wav",physicalSource);activeBuffer=buf();ScooterMusicMenu.Catalog.CODEC.encode(activeBuffer,sourced);check(ScooterMusicMenu.Catalog.CODEC.decode(activeBuffer).source().equals(physicalSource),"full source UUID roundtrip");activeBuffer.release();var sourceOptions=new ScooterMusicMenu.Options(true,false,true,37,"one.wav",physicalSource);activeBuffer=buf();ScooterMusicMenu.Options.CODEC.encode(activeBuffer,sourceOptions);check(ScooterMusicMenu.Options.CODEC.decode(activeBuffer).source().equals(physicalSource),"options source binding");activeBuffer.release();var sourcePart=new ScooterMusicMenu.CatalogPart(UUID.randomUUID(),0,true,false,true,false,true,true,37,"one.wav",physicalSource,"",List.of("one.wav"));activeBuffer=buf();ScooterMusicMenu.CatalogPart.CODEC.encode(activeBuffer,sourcePart);check(ScooterMusicMenu.CatalogPart.CODEC.decode(activeBuffer).source().equals(physicalSource),"chunk source binding");activeBuffer.release();check(new ScooterMusicMenu.Catalog(List.of(),true,false,true).source()==null,"legacy ctor has explicit absent source");
  timelines.clear();
  System.out.println("{\"success\":true,\"assertions\":"+checks+",\"actual_minecraft_codec\":true,\"native_game_launched\":false}");
 }
}
