package pl.aridlin.kukirin;
import java.nio.file.*;
import java.util.*;
import java.util.concurrent.CompletableFuture;
import net.minecraft.commands.Commands;
import net.minecraft.network.chat.Component;
import net.minecraft.server.level.ServerPlayer;
import net.minecraft.world.entity.EquipmentSlot;
import net.minecraft.world.item.*;
import net.minecraft.core.component.DataComponents;
import net.minecraft.world.item.component.CustomData;
import net.neoforged.bus.api.SubscribeEvent;
import net.neoforged.fml.common.EventBusSubscriber;
import net.neoforged.neoforge.event.RegisterCommandsEvent;
import net.neoforged.neoforge.event.tick.ServerTickEvent;
import net.neoforged.neoforge.network.PacketDistributor;
@EventBusSubscriber(modid="goplanska_kukirin")
public final class ScooterMusic {
 public static final int MAX_BYTES=16*1024*1024;
 private record Playback(Scooter scooter,UUID session,byte[] data,long until,Map<UUID,Integer> sent){}
 private static final Map<UUID,Playback> playing=new HashMap<>();
 private static final Map<UUID,UUID> loading=new HashMap<>();
 public static boolean permitted(Scooter s,ServerPlayer p){return s!=null&&(!ScooterEnchants.bound(s.getItemBySlot(EquipmentSlot.FEET))||ScooterEnchants.owned(s,p));}
 public static boolean insertDisc(Scooter s,ServerPlayer p,net.minecraft.world.InteractionHand hand){var disc=p.getItemInHand(hand);if(!disc.has(DataComponents.JUKEBOX_PLAYABLE)||!ScooterUpgradeRecipe.has(s.getItemBySlot(EquipmentSlot.FEET),"jukebox"))return false;stop(s);var item=s.getItemBySlot(EquipmentSlot.FEET).copy();var old=disc(item,s);if(!old.isEmpty())p.getInventory().placeItemBackInInventory(old);var copy=disc.copyWithCount(1);CustomData.update(DataComponents.CUSTOM_DATA,item,t->t.put("ScooterDisc",copy.save(s.registryAccess())));s.setItemSlot(EquipmentSlot.FEET,item);if(!p.isCreative())disc.shrink(1);s.startDisc();return true;}
 public static ItemStack disc(ItemStack item,Scooter s){var data=item.get(DataComponents.CUSTOM_DATA);return data==null?ItemStack.EMPTY:ItemStack.parseOptional(s.registryAccess(),data.copyTag().getCompound("ScooterDisc"));}
 public static void stop(Scooter s){loading.remove(s.getUUID());var old=playing.remove(s.getUUID());s.stopDisc();if(old!=null)for(var p:s.getServer().getPlayerList().getPlayers())if(old.sent.containsKey(p.getUUID()))PacketDistributor.sendToPlayer(p,new ScooterAudioPacket(s.getUUID(),old.session,0,0,new byte[0]));}
 public static java.util.List<String> songs(){var names=new java.util.TreeSet<String>();names.add("chiki_ride.wav");names.add("night_motor.wav");var folder=net.neoforged.fml.loading.FMLPaths.CONFIGDIR.get().resolve("goplanska-scooter/audio");if(Files.isDirectory(folder))try(var paths=Files.list(folder)){paths.filter(p->Files.isRegularFile(p)&&!Files.isSymbolicLink(p)).map(p->p.getFileName().toString()).filter(n->n.endsWith(".wav")&&n.matches("[A-Za-z0-9_. -]+\\.wav")&&!n.contains("..")).forEach(names::add);}catch(java.io.IOException ignored){}return java.util.List.copyOf(names);}
 public static int wav(ServerPlayer p,String name){var s=ScooterStorage.target(p);if(!permitted(s,p)||!ScooterUpgradeRecipe.has(s.getItemBySlot(EquipmentSlot.FEET),"noteblock")){p.displayClientMessage(Component.literal("Ride or aim at your scooter upgraded with a note block."),false);return 0;}if(!name.matches("[A-Za-z0-9_. -]+\\.wav")||name.contains("..")){p.displayClientMessage(Component.literal("Use a WAV filename from the server audio folder."),false);return 0;}if(loading.containsKey(s.getUUID()))return 0;if(playing.size()+loading.size()>=4){p.displayClientMessage(Component.literal("Four scooter WAV streams are already active."),false);return 0;}stop(s);UUID token=UUID.randomUUID();loading.put(s.getUUID(),token);var server=p.getServer();CompletableFuture.supplyAsync(()->{try{Path folder=net.neoforged.fml.loading.FMLPaths.CONFIGDIR.get().resolve("goplanska-scooter/audio");Files.createDirectories(folder);Path path=folder.resolve(name);byte[] bytes;if(Files.isRegularFile(path)&&!Files.isSymbolicLink(path)&&Files.size(path)<=MAX_BYTES)bytes=Files.readAllBytes(path);else if(name.equals("chiki_ride.wav")||name.equals("night_motor.wav")){try(var bundled=ScooterMusic.class.getResourceAsStream("/data/goplanska_kukirin/music/"+name)){if(bundled==null)throw new java.io.IOException("Bundled track missing");bytes=bundled.readNBytes(MAX_BYTES+1);}}else throw new java.io.IOException("Missing WAV or file exceeds 16 MiB");if(bytes.length>MAX_BYTES||bytes.length<44||!new String(bytes,0,4,java.nio.charset.StandardCharsets.US_ASCII).equals("RIFF")||!new String(bytes,8,4,java.nio.charset.StandardCharsets.US_ASCII).equals("WAVE"))throw new java.io.IOException("Not a RIFF WAV file");return bytes;}catch(Exception ex){throw new java.util.concurrent.CompletionException(ex);}}).whenComplete((bytes,error)->server.execute(()->{if(!token.equals(loading.get(s.getUUID()))||s.isRemoved())return;loading.remove(s.getUUID());if(error!=null){p.displayClientMessage(Component.literal("Cannot play WAV: "+error.getCause().getMessage()),false);return;}playing.put(s.getUUID(),new Playback(s,UUID.randomUUID(),bytes,s.level().getGameTime()+20*600,new HashMap<>()));p.displayClientMessage(Component.literal("Playing "+name+" from the scooter."),false);}));return 1;}
 @SubscribeEvent public static void commands(RegisterCommandsEvent e){e.getDispatcher().register(Commands.literal("scootermusic").then(Commands.literal("list").executes(c->{c.getSource().sendSuccess(()->Component.literal("Songs: "+String.join(", ",songs())+". Use /scootermusic <name>; note-block upgrade required."),false);return 1;})).then(Commands.literal("stop").executes(c->{var p=c.getSource().getPlayerOrException();var s=ScooterStorage.target(p);if(!permitted(s,p))return 0;stop(s);return 1;})).then(Commands.literal("disc").executes(c->{var p=c.getSource().getPlayerOrException();var s=ScooterStorage.target(p);if(!permitted(s,p)||!ScooterUpgradeRecipe.has(s.getItemBySlot(EquipmentSlot.FEET),"jukebox"))return 0;stop(s);s.startDisc();return 1;})).then(Commands.argument("wav",com.mojang.brigadier.arguments.StringArgumentType.greedyString()).suggests((c,b)->net.minecraft.commands.SharedSuggestionProvider.suggest(songs(),b)).executes(c->wav(c.getSource().getPlayerOrException(),com.mojang.brigadier.arguments.StringArgumentType.getString(c,"wav")))));}
 @SubscribeEvent public static void tick(ServerTickEvent.Post e){for(var playback:new ArrayList<>(playing.values())){var s=playback.scooter;if(s.isRemoved()||s.level().getGameTime()>playback.until){stop(s);continue;}for(var p:s.getServer().getPlayerList().getPlayers()){if(p.level()!=s.level()||p.distanceToSqr(s)>64*64){if(playback.sent.remove(p.getUUID())!=null)PacketDistributor.sendToPlayer(p,new ScooterAudioPacket(s.getUUID(),playback.session,0,0,new byte[0]));continue;}int offset=playback.sent.getOrDefault(p.getUUID(),0);for(int n=0;n<2&&offset<playback.data.length;n++){int end=Math.min(offset+32768,playback.data.length);PacketDistributor.sendToPlayer(p,new ScooterAudioPacket(s.getUUID(),playback.session,playback.data.length,offset,Arrays.copyOfRange(playback.data,offset,end)));offset=end;}playback.sent.put(p.getUUID(),offset);}}}
 @SubscribeEvent public static void shutdown(net.neoforged.neoforge.event.server.ServerStoppedEvent e){playing.clear();loading.clear();}
}
