package pl.aridlin.kukirin;
import net.minecraft.core.BlockPos;
import net.minecraft.server.level.ServerLevel;
import net.minecraft.world.level.block.*;
/** Bounded, loaded-chunk-only spawning. This never replaces a block or loads a chunk. */
@net.neoforged.fml.common.EventBusSubscriber(modid="goplanska_kukirin")
public final class ScooterRentalSpawner {
 @net.neoforged.bus.api.SubscribeEvent public static void commands(net.neoforged.neoforge.event.RegisterCommandsEvent e){var root=net.minecraft.commands.Commands.literal("scooterrental").requires(c->c.hasPermission(2));for(int brand=0;brand<3;brand++){final int b=brand;root.then(net.minecraft.commands.Commands.literal(new String[]{"lime","bolt","city"}[brand]).executes(c->{var p=c.getSource().getPlayerOrException();return spawn(p.serverLevel(),p.blockPosition().relative(p.getDirection(),3),b,false)==null?0:1;}));}root.then(net.minecraft.commands.Commands.literal("spawning").then(net.minecraft.commands.Commands.argument("enabled",com.mojang.brigadier.arguments.BoolArgumentType.bool()).executes(c->{boolean enabled=com.mojang.brigadier.arguments.BoolArgumentType.getBool(c,"enabled");ScooterRental.CONFIG.setSpawning(enabled);config=ScooterRental.CONFIG.get();c.getSource().sendSuccess(()->net.minecraft.network.chat.Component.literal("Rental spawning: "+enabled),true);return 1;})));e.getDispatcher().register(root);}
 private static RentalConfig.Settings config;private static long next;
 @net.neoforged.bus.api.SubscribeEvent public static void tick(net.neoforged.neoforge.event.tick.ServerTickEvent.Post e){var server=e.getServer();long now=server.overworld().getGameTime();if(now%100==0||config==null)config=ScooterRental.CONFIG.get();if(!config.spawning()||now<next)return;next=now+config.interval();var level=server.overworld();var rentals=new java.util.ArrayList<Scooter>();for(var entity:level.getAllEntities())if(entity instanceof Scooter s&&ScooterRental.isRental(s))rentals.add(s);if(rentals.size()>=config.total())return;
 for(var player:level.players()){if(player.isSpectator()||rentals.size()>=config.total())continue;long nearby=rentals.stream().filter(s->s.distanceToSqr(player)<96*96).count();if(nearby>=config.perPlayer())continue;BlockPos pos=null;
 if(level.random.nextDouble()<config.doorChance())pos=frontDoor(level,player.blockPosition());
 for(int attempt=0;pos==null&&attempt<8;attempt++){double angle=level.random.nextDouble()*Math.PI*2,radius=16+level.random.nextInt(33);var probe=player.blockPosition().offset((int)(Math.sin(angle)*radius),0,(int)(Math.cos(angle)*radius));if(!level.hasChunkAt(probe))continue;var surface=level.getHeightmapPos(net.minecraft.world.level.levelgen.Heightmap.Types.MOTION_BLOCKING_NO_LEAVES,probe);if(safe(level,surface))pos=surface;}
 if(pos!=null){var rental=spawn(level,pos,level.random.nextInt(3),level.random.nextDouble()<config.zombieChance());if(rental!=null)rentals.add(rental);}}
 }
 public static boolean safe(ServerLevel l,BlockPos p){return l.hasChunkAt(p)&&l.getWorldBorder().isWithinBounds(p)&&l.getBlockState(p.below()).isFaceSturdy(l,p.below(),net.minecraft.core.Direction.UP)&&l.getBlockState(p).isAir()&&l.getBlockState(p.above()).isAir()&&l.getFluidState(p).isEmpty();}
 static BlockPos frontDoor(ServerLevel l,BlockPos center){for(int x=-8;x<=8;x++)for(int z=-8;z<=8;z++)for(int y=-2;y<=2;y++){var p=center.offset(x,y,z);if(!l.hasChunkAt(p)||!(l.getBlockState(p).getBlock() instanceof DoorBlock))continue;if(l.getBlockState(p).getValue(DoorBlock.HALF)!=net.minecraft.world.level.block.state.properties.DoubleBlockHalf.LOWER)continue;var facing=l.getBlockState(p).getValue(DoorBlock.FACING);var outside=p.relative(facing,2);if(safe(l,outside))return outside;}return null;}
 public static Scooter spawn(ServerLevel l,BlockPos p,int brand,boolean jockey){if(!safe(l,p))return null;var s=Kukirin.SCOOTER.get().create(l);if(s==null)return null;s.moveTo(p.getX()+.5,p.getY(),p.getZ()+.5,l.random.nextFloat()*360,0);ScooterRental.initialize(s,brand);if(!l.noCollision(s))return null;l.addFreshEntity(s);if(jockey){var zombie=net.minecraft.world.entity.EntityType.ZOMBIE.create(l);if(zombie!=null){zombie.moveTo(s.position());zombie.setItemSlot(net.minecraft.world.entity.EquipmentSlot.HEAD,new net.minecraft.world.item.ItemStack(net.minecraft.world.item.Items.LEATHER_HELMET));l.addFreshEntity(zombie);zombie.startRiding(s,true);}}return s;}
}
