plugins {
    id 'eclipse'
    id 'idea'
    id 'maven-publish'
    id 'net.minecraftforge.gradle' version '[6.0,6.2)'
}

group = 'pl.aridlin'
version = '1.0.0'

base {
    archivesName = 'psychiatryk-roles'
}

java.toolchain.languageVersion = JavaLanguageVersion.of(17)

minecraft {
    mappings channel: 'official', version: '1.20.1'
}

repositories {
    mavenCentral()
}

dependencies {
    minecraft 'net.minecraftforge:forge:1.20.1-47.4.10'
    testImplementation 'org.junit.jupiter:junit-jupiter:5.10.2'
}

tasks.named('test', Test) {
    useJUnitPlatform()
}

tasks.named('jar', Jar) {
    manifest {
        attributes([
            'Specification-Title': 'Psychiatryk Roles',
            'Specification-Vendor': 'aridlin',
            'Specification-Version': '1',
            'Implementation-Title': project.name,
            'Implementation-Version': project.jar.archiveVersion,
            'Implementation-Vendor': 'aridlin',
            'MixinConfigs': 'psychiatryk_roles.mixins.json'
        ])
    }
    finalizedBy 'reobfJar'
}
