package pl.aridlin.partymarkers;
import java.util.UUID;
import net.minecraft.client.Minecraft;
import net.minecraft.world.phys.*;
import net.minecraft.world.entity.LivingEntity;
import net.minecraft.util.Mth;
import net.neoforged.neoforge.client.event.RenderLevelStageEvent;
import com.mojang.blaze3d.vertex.*;
import com.mojang.blaze3d.systems.RenderSystem;
import com.mojang.math.Axis;
import org.joml.*;
/** Shared rendering API: any provider can submit a stable ID, world bounds/model and color. */
public final class ChamsEffect {
 private ChamsEffect(){}
 public static boolean ready(){return ChamsPass.mask!=null&&ChamsPass.composite!=null;}
 private static void begin(RenderLevelStageEvent e){var mc=Minecraft.getInstance();mc.renderBuffers().bufferSource().endBatch();ChamsPass.begin(new Matrix4f(RenderSystem.getModelViewMatrix()).mul(e.getPoseStack().last().pose()).invert());}
 private static void end(RenderLevelStageEvent e,UUID id,int color,AABB body){end(e,id,color,body,true);}
 private static void end(RenderLevelStageEvent e,UUID id,int color,AABB body,boolean fill){var mc=Minecraft.getInstance();var camera=e.getCamera().getPosition();var center=body.getCenter().subtract(camera);var clip=new Matrix4f(e.getProjectionMatrix()).mul(RenderSystem.getModelViewMatrix()).mul(e.getPoseStack().last().pose()).transform(new Vector4f((float)center.x,(float)center.y,(float)center.z,1));var w=mc.getWindow();var anchor=new Vector2f((clip.x/clip.w+1)*.5f*w.getWidth(),(clip.y/clip.w+1)*.5f*w.getHeight());ChamsPass.crop(new Matrix4f(e.getProjectionMatrix()).mul(RenderSystem.getModelViewMatrix()).mul(e.getPoseStack().last().pose()),camera,body.inflate(.5));ChamsPass.end(id,color,0,camera,body,anchor,fill);}
 public static void box(RenderLevelStageEvent e,UUID id,AABB body,int color){box(e,id,body,color,true);}
 public static void box(RenderLevelStageEvent e,UUID id,AABB body,int color,boolean fill){if(!ready()||body.getXsize()<=0||body.getYsize()<=0||body.getZsize()<=0)return;var mc=Minecraft.getInstance();begin(e);var pose=e.getPoseStack();var camera=e.getCamera().getPosition();pose.pushPose();pose.translate(-camera.x,-camera.y,-camera.z);var buffer=mc.renderBuffers().bufferSource().getBuffer(ChamsPass.TYPE);var m=pose.last().pose();float x=(float)body.minX,y=(float)body.minY,z=(float)body.minZ,X=(float)body.maxX,Y=(float)body.maxY,Z=(float)body.maxZ;
  face(buffer,m,color,x,y,z,X,y,z,X,Y,z,x,Y,z);face(buffer,m,color,X,y,Z,x,y,Z,x,Y,Z,X,Y,Z);face(buffer,m,color,x,y,Z,x,y,z,x,Y,z,x,Y,Z);face(buffer,m,color,X,y,z,X,y,Z,X,Y,Z,X,Y,z);face(buffer,m,color,x,Y,z,X,Y,z,X,Y,Z,x,Y,Z);face(buffer,m,color,x,y,Z,X,y,Z,X,y,z,x,y,z);pose.popPose();mc.renderBuffers().bufferSource().endBatch(ChamsPass.TYPE);end(e,id,color,body,fill);}
 /** Highlight block/container bounds without treating those same cells as cover. */
 public static void blockBox(RenderLevelStageEvent e,UUID id,AABB body,int color){
  var excluded=new java.util.HashSet<net.minecraft.core.BlockPos>();
  for(int x=Mth.floor(body.minX);x<=Mth.floor(body.maxX-.0001);x++)for(int y=Mth.floor(body.minY);y<=Mth.floor(body.maxY-.0001);y++)for(int z=Mth.floor(body.minZ);z<=Mth.floor(body.maxZ-.0001);z++)excluded.add(new net.minecraft.core.BlockPos(x,y,z));
  var previous=ChamsPass.blockExclusions;ChamsPass.blockExclusions=excluded;
  try{box(e,id,body,color);}finally{ChamsPass.blockExclusions=previous;}
 }
 public static void chalk(RenderLevelStageEvent e,UUID id,AABB bounds,int color){if(!ready())return;var mc=Minecraft.getInstance();begin(e);var pose=e.getPoseStack();var camera=e.getCamera().getPosition();var center=bounds.getCenter();pose.pushPose();pose.translate(center.x-camera.x,center.y-camera.y,center.z-camera.z);pose.mulPose(e.getCamera().rotation());var b=mc.renderBuffers().bufferSource().getBuffer(ChamsPass.TYPE);for(float angle:new float[]{45,135}){pose.pushPose();pose.mulPose(Axis.ZP.rotationDegrees(angle));face(b,pose.last().pose(),color,-.36f,-.025f,0,.36f,-.025f,0,.36f,.025f,0,-.36f,.025f,0);pose.popPose();}pose.popPose();mc.renderBuffers().bufferSource().endBatch(ChamsPass.TYPE);end(e,id,color,bounds.inflate(.3));}
 public static void plane(RenderLevelStageEvent e,UUID id,AABB body,int color){plane(e,id,body,color,true);}
 public static void plane(RenderLevelStageEvent e,UUID id,AABB body,int color,boolean fill){if(!ready()||body.getXsize()<=0||body.getZsize()<=0)return;var mc=Minecraft.getInstance();begin(e);var pose=e.getPoseStack();var camera=e.getCamera().getPosition();pose.pushPose();pose.translate(-camera.x,-camera.y,-camera.z);float x=(float)body.minX,X=(float)body.maxX,y=(float)body.minY+.025f,z=(float)body.minZ,Z=(float)body.maxZ;face(mc.renderBuffers().bufferSource().getBuffer(ChamsPass.TYPE),pose.last().pose(),color,x,y,z,X,y,z,X,y,Z,x,y,Z);pose.popPose();mc.renderBuffers().bufferSource().endBatch(ChamsPass.TYPE);end(e,id,color,new AABB(body.minX,y-.001,body.minZ,body.maxX,y+.001,body.maxZ),fill);}
 private static void face(VertexConsumer b,Matrix4f m,int color,float... xyz){for(int i=0;i<12;i+=3)b.addVertex(m,xyz[i],xyz[i+1],xyz[i+2]).setColor(color|0xff000000).setUv(0,0).setOverlay(0).setLight(0xf000f0).setNormal(0,1,0);}
 static final VertexConsumer EMPTY=new VertexConsumer(){public VertexConsumer addVertex(float x,float y,float z){return this;}public VertexConsumer setColor(int r,int g,int b,int a){return this;}public VertexConsumer setUv(float u,float v){return this;}public VertexConsumer setUv1(int u,int v){return this;}public VertexConsumer setUv2(int u,int v){return this;}public VertexConsumer setNormal(float x,float y,float z){return this;}};
 public static void item(RenderLevelStageEvent e,net.minecraft.world.entity.item.ItemEntity item,int color){if(!ready()||ChamsPass.itemMask==null)return;var mc=Minecraft.getInstance();float partial=e.getPartialTick().getGameTimeDeltaPartialTick(false);Vec3 pos=new Vec3(Mth.lerp(partial,item.xOld,item.getX()),Mth.lerp(partial,item.yOld,item.getY()),Mth.lerp(partial,item.zOld,item.getZ()));begin(e);var pose=e.getPoseStack();var camera=e.getCamera().getPosition();pose.pushPose();pose.translate(pos.x-camera.x,pos.y-camera.y,pos.z-camera.z);var used=new java.util.HashSet<net.minecraft.client.renderer.RenderType>();net.minecraft.client.renderer.MultiBufferSource source=type->{if(type.toString().toLowerCase(java.util.Locale.ROOT).contains("glint"))return EMPTY;var maskType=ChamsPass.itemType(type);used.add(maskType);return mc.renderBuffers().bufferSource().getBuffer(maskType);};mc.getEntityRenderDispatcher().getRenderer(item).render(item,item.getYRot(),partial,pose,source,0xf000f0);pose.popPose();for(var type:used)mc.renderBuffers().bufferSource().endBatch(type);end(e,item.getUUID(),color,item.getBoundingBox().inflate(.4,.5,.4).move(pos.subtract(item.position())));}
 public static void entity(RenderLevelStageEvent e,LivingEntity entity,int color){float partial=e.getPartialTick().getGameTimeDeltaPartialTick(false);entityAt(e,entity,color,new Vec3(Mth.lerp(partial,entity.xOld,entity.getX()),Mth.lerp(partial,entity.yOld,entity.getY()),Mth.lerp(partial,entity.zOld,entity.getZ())));}
 public static boolean hiddenFirstPersonVehicle(net.minecraft.world.entity.Entity entity){var mc=Minecraft.getInstance();return entity instanceof pl.aridlin.kukirin.Scooter&&mc.player!=null&&mc.options.getCameraType().isFirstPerson()&&entity==mc.player.getVehicle();}
 public static void entityAt(RenderLevelStageEvent e,LivingEntity entity,int color,Vec3 pos){if(!ready()||hiddenFirstPersonVehicle(entity))return;genericEntity(e,entity,color,pos);}
 @SuppressWarnings({"rawtypes","unchecked"}) private static void genericEntity(RenderLevelStageEvent e,LivingEntity entity,int color,Vec3 pos){var mc=Minecraft.getInstance();begin(e);var pose=e.getPoseStack();var camera=e.getCamera().getPosition();pose.pushPose();var renderer=mc.getEntityRenderDispatcher().getRenderer(entity);float partial=e.getPartialTick().getGameTimeDeltaPartialTick(false);var offset=renderer.getRenderOffset(entity,partial);pose.translate(pos.x-camera.x+offset.x,pos.y-camera.y+offset.y,pos.z-camera.z+offset.z);var used=new java.util.HashSet<net.minecraft.client.renderer.RenderType>();net.minecraft.client.renderer.MultiBufferSource mask=type->{if(type.format()!=com.mojang.blaze3d.vertex.DefaultVertexFormat.NEW_ENTITY||type.toString().toLowerCase(java.util.Locale.ROOT).contains("glint"))return EMPTY;var pass=ChamsPass.itemType(type);used.add(pass);return mc.renderBuffers().bufferSource().getBuffer(pass);};renderer.render(entity,Mth.rotLerp(e.getPartialTick().getGameTimeDeltaPartialTick(false),entity.yRotO,entity.getYRot()),e.getPartialTick().getGameTimeDeltaPartialTick(false),pose,mask,0xf000f0);pose.popPose();for(var type:used)mc.renderBuffers().bufferSource().endBatch(type);end(e,entity.getUUID(),color,entity.getBoundingBox().inflate(.4).move(pos.subtract(entity.position())));}

}
