package pl.aridlin.peebqa;
import com.google.gson.*;
import com.mojang.authlib.GameProfile;
import com.mojang.blaze3d.platform.InputConstants;
import java.nio.file.*;
import java.util.*;
import java.util.concurrent.*;
import java.util.function.Supplier;
import net.minecraft.client.*;
import net.minecraft.client.player.RemotePlayer;
import net.minecraft.client.gui.screens.inventory.InventoryScreen;
import net.minecraft.core.BlockPos;
import net.minecraft.server.MinecraftServer;
import net.minecraft.server.level.ServerPlayer;
import net.minecraft.world.entity.EquipmentSlot;
import net.minecraft.world.item.*;
import net.minecraft.world.level.*;
import net.minecraft.world.level.block.Blocks;
import net.minecraft.world.phys.Vec3;
import net.neoforged.fml.common.Mod;
import net.neoforged.neoforge.common.NeoForge;
import net.neoforged.neoforge.client.event.ClientTickEvent;
import net.neoforged.neoforge.client.event.InputEvent;
import net.neoforged.neoforge.event.entity.player.PlayerEvent;
import pl.aridlin.psychiatrykroles.peeb.*;
import pl.aridlin.psychiatrykroles.peeb.client.*;
@Mod("psychiatryk_peeb_qa")
public final class PeebQA {
 final Path out=Path.of(System.getProperty("peebqa.output"));final JsonArray checks=new JsonArray();final JsonArray samples=new JsonArray();
 MinecraftServer server;UUID playerId;RemotePlayer remote;volatile boolean prepared;volatile Throwable preparationError;CompletableFuture<?> pending;int phase,ticks,warm;boolean done;long start=System.nanoTime();
 Vec3 anchor,startPosition;double startDistance,startLength,lastDistance,minY=Double.POSITIVE_INFINITY;float yaw;int[] ditherPixels;int imageWidth,imageHeight;
 public PeebQA(){NeoForge.EVENT_BUS.addListener(this::login);NeoForge.EVENT_BUS.addListener(this::tick);}
 ServerPlayer player(){return server.getPlayerList().getPlayer(playerId);}<T>CompletableFuture<T> call(Supplier<T> b){return server.submit(b::get);}
 void check(boolean ok,String name){var r=new JsonObject();r.addProperty("name",name);r.addProperty("passed",ok);checks.add(r);if(!ok)throw new AssertionError(name);}
 void next(){phase++;ticks=0;}
 void login(PlayerEvent.PlayerLoggedInEvent e){if(!(e.getEntity() instanceof ServerPlayer p))return;try{server=p.server;playerId=p.getUUID();var l=p.serverLevel();p.setGameMode(GameType.SURVIVAL);p.getInventory().clearContent();
 for(var r:List.of(GameRules.RULE_DOMOBSPAWNING,GameRules.RULE_DAYLIGHT,GameRules.RULE_WEATHER_CYCLE))l.getGameRules().getRule(r).set(false,server);
 l.getGameRules().getRule(GameRules.RULE_KEEPINVENTORY).set(true,server);l.setDayTime(6000);
 for(int x=-12;x<=12;x++)for(int z=-12;z<=12;z++)for(int y=79;y<=86;y++)l.setBlock(new BlockPos(x,y,z),y==79?Blocks.SMOOTH_STONE.defaultBlockState():Blocks.AIR.defaultBlockState(),3);
 for(int x=-5;x<=5;x++)for(int y=80;y<=86;y++)l.setBlock(new BlockPos(x,y,6),Blocks.STONE.defaultBlockState(),3);
 p.teleportTo(l,.5,80,.5,0,0);p.setRespawnPosition(l.dimension(),new BlockPos(0,80,0),0,true,false);p.getInventory().setItem(0,new ItemStack(PeebMode.PEEB.get()));prepared=true;
 }catch(Throwable t){preparationError=t;}}
 void click(int action){var e=new InputEvent.MouseButton.Pre(0,action,0);NeoForge.EVENT_BUS.post(e);check(e.isCanceled(),"Actual Peeb LMB event owns grapple input action "+action);}
 int[] image(String name)throws Exception{var mc=Minecraft.getInstance();try(var im=Screenshot.takeScreenshot(mc.getMainRenderTarget())){im.writeToFile(out.resolve(name+".png"));imageWidth=im.getWidth();imageHeight=im.getHeight();var a=new int[imageWidth*imageHeight];for(int y=0;y<imageHeight;y++)for(int x=0;x<imageWidth;x++)a[y*imageWidth+x]=im.getPixelRGBA(x,y);return a;}}
 void tick(ClientTickEvent.Post e){if(done)return;try{if(preparationError!=null)throw new RuntimeException(preparationError);if(System.nanoTime()-start>540_000_000_000L)throw new AssertionError("Overall native QA timeout phase "+phase);var mc=Minecraft.getInstance();if(!prepared||mc.level==null||mc.player==null)return;if(warm++<50)return;mc.mouseHandler.releaseMouse();if(++ticks>300)throw new AssertionError("Phase timeout "+phase);if(pending!=null){if(!pending.isDone())return;pending.join();pending=null;}
 switch(phase){
 case 0->{check(PeebClient.localActive(),"Held Peeb acquires native third-person mode");check(mc.options.getCameraType()==CameraType.THIRD_PERSON_BACK,"Native back camera enabled");check(PeebStyle.shader!=null,"Peeb shader compiled by actual OpenGL runtime");check(PeebClient.target(1).isPresent()&&PeebClient.target(1).get().eligible(),"Actual camera-centered wall reticle has server-eligible target");
 var camera=mc.gameRenderer.getMainCamera();var above=PeebClient.cameraFrame(camera,1);check(Math.abs(above.position().y-mc.player.getY()-2.1)<.01,"Default Peeb camera pivot is 2.1 blocks above feet");check(camera.getPosition().y>mc.player.getEyeY()+.4,"Actual native camera is positioned above Peeb head");check(PeebClient.target(1).get().point().y>mc.player.getY()+1.9,"Above-head camera target is aimed over the character");image("00-default-above-head-native");PeebClient.cameraProfile(new PeebClient.CameraProfile(6,1.2f,-90,90));
 remote=new RemotePlayer(mc.level,new GameProfile(UUID.fromString("70656562-1111-2222-3333-000000000002"),"Opaque Peeb Fixture"));remote.setId(-702);remote.moveTo(2.5,80,2.5,180,0);remote.yBodyRot=remote.yBodyRotO=180;remote.yHeadRot=remote.yHeadRotO=180;remote.setItemSlot(EquipmentSlot.MAINHAND,new ItemStack(PeebMode.PEEB.get()));mc.level.addEntity(remote);next();}
 case 1->{if(ticks<12)return;check(NativeDraws.local>5&&NativeDraws.localTarget>5,"Native local draw uploads target-relative dither fade");check(NativeDraws.remote>5&&PeebRenderer.renderedPose(remote)!=null,"Remote Peeb gets separate opaque shader draw");check(NativeDraws.depthCorrect>=NativeDraws.local+NativeDraws.remote-2,"Native Peeb batches retain LEQUAL depth testing");check(PeebRenderer.renderedLocalDitherBatches>5&&PeebRenderer.renderedReticles>5,"Actual local character and target ring both submitted");ditherPixels=image("01-local-target-dither-native");NativeDraws.forceFadeOff=true;next();}
 case 2->{if(ticks<4)return;var opaque=image("02-qa-only-opaque-comparison");int differences=0,central=0;for(int y=100;y<imageHeight-100;y++)for(int x=100;x<imageWidth-100;x++){int i=y*imageWidth+x;if(ditherPixels[i]!=opaque[i]){differences++;if(Math.abs(x-imageWidth/2)<180&&Math.abs(y-imageHeight/2)<180)central++;}}check(central>100,"Native fade-on/off frame pair changes the body-over-target region");var row=new JsonObject();row.addProperty("name","native_dither_pair");row.addProperty("changed_pixels",differences);row.addProperty("central_changed_pixels",central);samples.add(row);NativeDraws.forceFadeOff=false;PeebClient.cameraProfile(new PeebClient.CameraProfile(6,2.1f,-90,90));mc.level.removeEntity(remote.getId(),net.minecraft.world.entity.Entity.RemovalReason.DISCARDED);yaw=mc.player.getYRot();mc.player.turn(0,-1000);next();}
 case 3->{if(ticks<3)return;check(PeebClient.cameraFrame(mc.gameRenderer.getMainCamera(),1).pitch()==-90,"Native mouse look reaches straight up");mc.player.turn(0,2000);next();}
 case 4->{if(ticks<3)return;check(PeebClient.cameraFrame(mc.gameRenderer.getMainCamera(),1).pitch()==90,"Native mouse look reaches straight down");mc.player.setXRot(0);mc.player.xRotO=0;PeebClientBootstrap.FREELOOK.setDown(true);mc.player.turn(300,-200);next();}
 case 5->{if(ticks<3)return;var f=PeebClient.cameraFrame(mc.gameRenderer.getMainCamera(),1);check(Math.abs(mc.player.getYRot()-yaw)<.01&&Math.abs(f.yaw()-yaw-45)<.1,"Freelook independently orbits without changing movement yaw");check(Math.abs(f.pitch()+30)<.1,"Freelook independent pitch reaches requested native orbit");PeebClientBootstrap.FREELOOK.setDown(false);next();}
 case 6->{if(ticks<25)return;var f=PeebClient.cameraFrame(mc.gameRenderer.getMainCamera(),1);check(Math.abs(f.yaw()-mc.player.getYRot())<.1,"Freelook smoothly returns");
 var other=new KeyMapping("qa.othermod",InputConstants.Type.KEYSYM,org.lwjgl.glfw.GLFW.GLFW_KEY_F8,KeyMapping.CATEGORY_MISC);PeebClientBootstrap.INTERACT.setKey(other.getKey());PeebBindings.resolve(new KeyMapping[]{PeebClientBootstrap.INTERACT,PeebClientBootstrap.FREELOOK,other,mc.options.keyInventory});check(PeebClientBootstrap.INTERACT.isUnbound()&&other.getKey().getValue()==org.lwjgl.glfw.GLFW.GLFW_KEY_F8,"Peeb interaction yields arbitrary mod binding without modifying it");PeebBindings.audit(mc);for(var own:List.of(PeebClientBootstrap.INTERACT,PeebClientBootstrap.FREELOOK))for(var key:mc.options.keyMappings)if(key!=own&&!key.isUnbound()&&!own.isUnbound())check(!own.getKey().equals(key.getKey()),"Peeb extra binding does not conflict with "+key.getName());
 pending=call(()->{player().getInventory().clearContent();player().setItemSlot(EquipmentSlot.CHEST,new ItemStack(PeebMode.PEEB.get()));return true;});next();}
 case 7->{if(ticks<12)return;check(PeebClient.localActive()&&PeebMode.worn(mc.player),"Chest-worn Peeb activates native mode");KeyMapping.click(mc.options.keyInventory.getKey());next();}
 case 8->{if(ticks<3)return;check(mc.screen instanceof InventoryScreen,"Native inventory key opens inventory while Peeb is worn");mc.setScreen(null);pending=call(()->{player().setItemSlot(EquipmentSlot.CHEST,ItemStack.EMPTY);player().getInventory().setItem(0,new ItemStack(PeebMode.PEEB.get()));player().teleportTo(player().serverLevel(),.5,80,.5,0,0);player().setDeltaMovement(Vec3.ZERO);return true;});next();}
 case 9->{if(ticks<20)return;var t=PeebClient.target(1);check(t.isPresent()&&t.get().eligible(),"Wall target restored before real grapple input");anchor=t.get().point();startPosition=mc.player.position();startDistance=PeebAttachment.pivot(mc.player,PeebAttachment.yaw(mc.player)).distanceTo(anchor);click(1);next();}
 case 10->{if(ticks<5)return;check(PeebClient.grapple(mc.player).isPresent(),"Real held mouse input receives server accepted wall tether");double earlyDistance=PeebAttachment.pivot(mc.player,PeebClient.grapple(mc.player).get().attachmentYaw()).distanceTo(anchor);var early=new JsonObject();early.addProperty("name","quick_first_five_native_ticks");early.addProperty("initial_pivot_distance",startDistance);early.addProperty("current_pivot_distance",earlyDistance);early.addProperty("current_feet_distance",mc.player.position().distanceTo(anchor));early.addProperty("pivot_closure",startDistance-earlyDistance);samples.add(early);check(earlyDistance<startDistance-.7,"Quick winch moves toward the anchor within first five native ticks");startLength=PeebClient.grapple(mc.player).get().length();lastDistance=mc.player.position().distanceTo(anchor);mc.options.keyLeft.setDown(true);next();}
 case 11->{var gr=PeebClient.grapple(mc.player);if(ticks%5==0){var row=new JsonObject();row.addProperty("tick",ticks);row.addProperty("distance",mc.player.position().distanceTo(anchor));row.addProperty("pivot_distance",gr.map(g->PeebAttachment.pivot(mc.player,g.attachmentYaw()).distanceTo(anchor)).orElse(-1.));row.addProperty("rest_length",gr.map(PeebClient.Grapple::length).orElse(-1.));row.addProperty("x",mc.player.getX());row.addProperty("y",mc.player.getY());row.addProperty("z",mc.player.getZ());samples.add(row);}if(ticks<20)return;mc.options.keyLeft.setDown(false);check(gr.isPresent(),"Tether stays attached through tangential steering");check(Math.abs(mc.player.getX()-startPosition.x)>.1,"Actual lateral movement remains during rope pulling");check(gr.get().length()<2.1,"Quick winch rest length reaches near two-block resting length within 20 input ticks");check(PeebAttachment.pivot(mc.player,gr.get().attachmentYaw()).distanceTo(anchor)<startDistance-2,"Quick native pull closes more than two blocks within 20 input ticks with steering");image("03a-quick-pull-after20-native");next();}
 case 12->{if(ticks<15)return;var gr=PeebClient.grapple(mc.player);check(gr.isPresent(),"Wall tether remains attached while rope reels");check(gr.get().length()<startLength-.4,"Authoritative synced rope rest length decreases over actual ticks");check(mc.player.position().distanceTo(anchor)<lastDistance-.35,"Actual player is pulled closer to wall anchor");check(NativeDraws.ropes>10&&NativeDraws.vertices==96,"Native rope draw submits 24 flexible quad segments");check(NativeDraws.endpointError<1e-6,"Native rope vertex endpoints align with actual rendered tusk tip and anchor");check(PeebRenderer.renderedTuskTip(mc.player).distanceTo(PeebAttachment.pivot(mc.player.getPosition(1),gr.get().attachmentYaw()))<.25,"Actual character swings from its tusk attachment pivot");image("03-pulling-flexible-rope-native");click(0);next();}
 case 13->{if(ticks<10)return;check(PeebClient.grapple(mc.player).isEmpty(),"Mouse release clears native client rope");pending=call(()->{check(PeebGrapple.snapshot(player()).anchor().isEmpty(),"Mouse release clears authoritative server rope");player().teleportTo(player().serverLevel(),.5,80,.5,0,65);player().setDeltaMovement(Vec3.ZERO);return true;});next();}
 case 14->{if(ticks<20)return;var t=PeebClient.target(1);check(t.isPresent()&&t.get().eligible()&&t.get().normal().y>.99,"Native downward camera selects exposed floor");anchor=t.get().point();click(1);next();}
 case 15->{if(ticks<6)return;check(PeebClient.grapple(mc.player).isPresent(),"Floor grapple accepted by actual packet server handler");mc.options.keyLeft.setDown(true);minY=mc.player.getY();next();}
 case 16->{minY=Math.min(minY,mc.player.getY());if(ticks<25)return;mc.options.keyLeft.setDown(false);check(minY>=79.95,"Floor rope does not drive player below supporting ground");check(mc.player.position().lengthSqr()>0&&Double.isFinite(mc.player.position().lengthSqr()),"Floor movement remains finite");image("04-floor-rope-native");click(0);pending=call(()->{player().getInventory().setItem(0,new ItemStack(Items.STICK));return true;});next();}
 case 17->{if(ticks<12)return;check(!PeebClient.localActive()&&PeebClient.grapple(mc.player).isEmpty(),"Putting Peeb away clears mode and rope");pending=call(()->{check(PeebGrapple.snapshot(player()).anchor().isEmpty(),"Putaway clears authoritative rope state");return true;});next();}
 case 18->{finish(true,null);}
 }
 }catch(Throwable t){finish(false,t);}}
 void finish(boolean ok,Throwable error){if(done)return;done=true;var mc=Minecraft.getInstance();NativeDraws.forceFadeOff=false;mc.options.keyLeft.setDown(false);mc.options.keyUp.setDown(false);PeebClientBootstrap.FREELOOK.setDown(false);PeebPackets.release();try{var r=new JsonObject();r.addProperty("success",ok);r.addProperty("candidate_sha256",System.getProperty("peebqa.sha256"));r.addProperty("helper_sha256",System.getProperty("peebqa.helperSha256"));r.addProperty("phase",phase);r.add("checks",checks);r.add("native_samples",samples);r.addProperty("rendered_local_batches",NativeDraws.local);r.addProperty("rendered_remote_batches",NativeDraws.remote);r.addProperty("rendered_depth_lequal",NativeDraws.depthCorrect);r.addProperty("rope_vertices",NativeDraws.vertices);r.addProperty("rope_endpoint_error",NativeDraws.endpointError);r.addProperty("human_grapple_feel_verified",false);r.addProperty("shaders_enabled",false);r.addProperty("native_frame_pair_qa_override_only",true);r.addProperty("dither_fixture_camera_height",1.2);r.addProperty("default_and_pull_camera_height",2.1);if(error!=null){r.addProperty("error",error.toString());error.printStackTrace();}Files.writeString(out.resolve("runtime-report.json"),new GsonBuilder().setPrettyPrinting().create().toJson(r)+"\n");}catch(Throwable t){t.printStackTrace();}mc.stop();}
}
