package pl.aridlin.spectate;
import java.util.*;
import net.minecraft.commands.*;
import net.minecraft.commands.arguments.EntityArgument;
import net.minecraft.network.chat.Component;
import net.minecraft.server.level.ServerPlayer;
import net.minecraft.world.level.GameType;
import net.neoforged.fml.common.Mod;
import net.neoforged.bus.api.IEventBus;
import net.neoforged.neoforge.common.NeoForge;
import net.neoforged.neoforge.event.RegisterCommandsEvent;
import net.neoforged.neoforge.event.tick.ServerTickEvent;
import net.neoforged.neoforge.network.PacketDistributor;
import dev.ClasherHD.bodycam.util.BodycamHelper;
import dev.ClasherHD.bodycam.network.ServerNetworking;
@Mod("goplanska_spectate")
public final class AdminSpectate {
 record Session(UUID target){ }static final Map<UUID,Session> sessions=new HashMap<>();
 public AdminSpectate(IEventBus bus){bus.addListener((net.neoforged.neoforge.network.event.RegisterPayloadHandlersEvent e)->e.registrar("1").playToClient(SpectateData.TYPE,SpectateData.CODEC,(data,c)->c.enqueueWork(()->SpectateClient.receive(data))));NeoForge.EVENT_BUS.addListener(this::commands);NeoForge.EVENT_BUS.addListener(this::tick);NeoForge.EVENT_BUS.addListener((net.neoforged.neoforge.event.entity.player.PlayerEvent.PlayerLoggedOutEvent e)->{if(e.getEntity() instanceof ServerPlayer p)stop(p);});NeoForge.EVENT_BUS.addListener((net.neoforged.neoforge.event.server.ServerStoppingEvent e)->{for(var p:e.getServer().getPlayerList().getPlayers())if(sessions.containsKey(p.getUUID()))stop(p);sessions.clear();});}
 void commands(RegisterCommandsEvent e){e.getDispatcher().register(Commands.literal("spectate").requires(s->s.hasPermission(2)).executes(c->stop(c.getSource().getPlayerOrException())).then(Commands.literal("stop").executes(c->stop(c.getSource().getPlayerOrException()))).then(Commands.argument("target",EntityArgument.player()).executes(c->start(c.getSource().getPlayerOrException(),EntityArgument.getPlayer(c,"target")))).then(Commands.literal("view").then(Commands.literal("first").executes(c->view(c.getSource().getPlayerOrException(),0))).then(Commands.literal("third").executes(c->view(c.getSource().getPlayerOrException(),1)))));}
 int start(ServerPlayer p,ServerPlayer target){if(p==target){p.sendSystemMessage(Component.literal("Choose another player."));return 0;}if(!p.connection.hasChannel(SpectateData.TYPE)){p.sendSystemMessage(Component.literal("Install the matching spectate client mod."));return 0;}stop(p);ServerNetworking.cleanupDummy(p);var d=BodycamHelper.getPersistentData(p);d.putInt("bodycam_original_gamemode",p.gameMode.getGameModeForPlayer().getId());d.putString("bodycam_orig_dim",p.level().dimension().location().toString());d.putDouble("bodycam_orig_x",p.getX());d.putDouble("bodycam_orig_y",p.getY());d.putDouble("bodycam_orig_z",p.getZ());d.putFloat("bodycam_orig_yrot",p.getYRot());d.putFloat("bodycam_orig_xrot",p.getXRot());d.putDouble("bodycam_orig_motx",0);d.putDouble("bodycam_orig_moty",0);d.putDouble("bodycam_orig_motz",0);d.putFloat("bodycam_orig_fall",0);
 var dummy=new dev.ClasherHD.bodycam.entity.HologramDummyEntity(dev.ClasherHD.bodycam.Bodycam.HOLOGRAM_DUMMY.get(),p.serverLevel());dummy.moveTo(p.getX(),p.getY(),p.getZ(),p.getYRot(),p.getXRot());dummy.setYHeadRot(p.getYHeadRot());dummy.setNoGravity(true);dummy.setInvulnerable(true);dummy.getEntityData().set(dev.ClasherHD.bodycam.entity.BodycamDummyEntity.OWNER_UUID,Optional.of(p.getUUID()));dummy.getEntityData().set(dev.ClasherHD.bodycam.entity.BodycamDummyEntity.OWNER_NAME,p.getGameProfile().getName());dummy.setCustomName(p.getName());dummy.setHealth(p.getHealth());for(var slot:net.minecraft.world.entity.EquipmentSlot.values())dummy.setItemSlot(slot,p.getItemBySlot(slot).copy());p.serverLevel().addFreshEntity(dummy);d.putUUID("bodycam_dummy_uuid",dummy.getUUID());d.putBoolean("bodycam_active",true);d.putUUID("bodycam_target_uuid",target.getUUID());d.putBoolean("bodycam_bypass_dist",true);d.putBoolean("GoplanskaAdminSpectate",true);p.setGameMode(GameType.SPECTATOR);if(p.level()!=target.level()){d.putBoolean("bodycam_allow_teleport",true);p.teleportTo(target.serverLevel(),target.getX(),target.getY(),target.getZ(),target.getYRot(),target.getXRot());d.remove("bodycam_allow_teleport");}p.setCamera(target);sessions.put(p.getUUID(),new Session(target.getUUID()));send(p,target,0);p.sendSystemMessage(Component.literal("Spectating "+target.getGameProfile().getName()+". Your body stays behind. F5 or /spectate view first|third. /spectate stop returns."));return 1;}
 static int stop(ServerPlayer p){boolean active=sessions.remove(p.getUUID())!=null||BodycamHelper.getPersistentData(p).getBoolean("GoplanskaAdminSpectate");if(!active)return 0;ServerNetworking.executeReset(p);BodycamHelper.getPersistentData(p).remove("GoplanskaAdminSpectate");if(p.connection.hasChannel(SpectateData.TYPE))PacketDistributor.sendToPlayer(p,SpectateData.stop());return 1;}
 int view(ServerPlayer p,int mode){var s=sessions.get(p.getUUID());if(s==null)return 0;var target=p.getServer().getPlayerList().getPlayer(s.target());if(target!=null)send(p,target,mode);return 1;}
 void tick(ServerTickEvent.Post e){if(e.getServer().getTickCount()%2!=0)return;for(var entry:new ArrayList<>(sessions.entrySet())){var p=e.getServer().getPlayerList().getPlayer(entry.getKey());var target=e.getServer().getPlayerList().getPlayer(entry.getValue().target());if(p==null){sessions.remove(entry.getKey());continue;}if(target==null||!p.hasPermissions(2)||!BodycamHelper.getPersistentData(p).getBoolean("bodycam_active")){stop(p);continue;}send(p,target,-1);}}
 void send(ServerPlayer p,ServerPlayer target,int view){var inv=new ArrayList<net.minecraft.world.item.ItemStack>();for(int i=0;i<target.getInventory().getContainerSize();i++)inv.add(target.getInventory().getItem(i).copy());var slots=new ArrayList<net.minecraft.world.item.ItemStack>();String menu="";if(target.containerMenu!=target.inventoryMenu){menu=target.containerMenu.getClass().getSimpleName();for(var slot:target.containerMenu.slots){if(slots.size()>=512)break;slots.add(slot.getItem().copy());}}PacketDistributor.sendToPlayer(p,new SpectateData(true,target.getUUID(),target.getGameProfile().getName(),target.getInventory().selected,inv,menu,slots,view));}
}
