"""Exercise the actual Peeb admin screen with headless UI doubles; no game launch."""
from pathlib import Path
import subprocess,json,hashlib,shutil
R=Path(__file__).resolve().parents[1];B=R/'build/headless-gui';S=B/'src';C=B/'classes';shutil.rmtree(B,ignore_errors=True);C.mkdir(parents=True)
def write(name,value):
 p=S/name;p.parent.mkdir(parents=True,exist_ok=True);p.write_text(value)
write('net/minecraft/network/chat/Component.java','''package net.minecraft.network.chat; public record Component(String text){public static Component literal(String s){return new Component(s);} public static Component empty(){return literal("");}}''')
write('net/minecraft/client/gui/Font.java','''package net.minecraft.client.gui;public class Font{}''')
write('net/minecraft/client/gui/GuiGraphics.java','''package net.minecraft.client.gui;import net.minecraft.network.chat.Component;public class GuiGraphics{public void drawCenteredString(Font f,Component c,int x,int y,int color){}}''')
write('net/minecraft/client/Minecraft.java','''package net.minecraft.client;import net.minecraft.client.gui.screens.Screen;public class Minecraft{private static final Minecraft INSTANCE=new Minecraft();public Screen screen;public static Minecraft getInstance(){return INSTANCE;}public void setScreen(Screen s){screen=s;if(s!=null)s.headlessInit();}}''')
write('net/minecraft/client/gui/screens/Screen.java','''package net.minecraft.client.gui.screens;import net.minecraft.client.Minecraft;import net.minecraft.client.gui.Font;import net.minecraft.client.gui.GuiGraphics;import net.minecraft.network.chat.Component;public class Screen{protected Minecraft minecraft=Minecraft.getInstance();protected Font font=new Font();protected Component title;protected int width=800,height=600;public final java.util.List<Object> widgets=new java.util.ArrayList<>();public Screen(Component c){title=c;}protected void init(){}public void headlessInit(){init();}protected <T> T addRenderableWidget(T v){widgets.add(v);return v;}protected void rebuildWidgets(){widgets.clear();init();}protected void renderBackground(GuiGraphics g,int x,int y,float t){}public void render(GuiGraphics g,int x,int y,float t){}public void onClose(){}public boolean isPauseScreen(){return false;}}''')
write('net/minecraft/client/gui/components/AbstractSliderButton.java','''package net.minecraft.client.gui.components;import net.minecraft.network.chat.Component;public abstract class AbstractSliderButton{protected double value;public int x,y,w,h;public Component message;public AbstractSliderButton(int x,int y,int w,int h,Component c,double value){this.x=x;this.y=y;this.w=w;this.h=h;this.value=value;this.message=c;}protected abstract void updateMessage();protected abstract void applyValue();public void setMessage(Component c){message=c;}public void testSet(double v){value=v;applyValue();}public double normalized(){return value;}}''')
write('net/minecraft/client/gui/components/Button.java','''package net.minecraft.client.gui.components;import net.minecraft.network.chat.Component;import java.util.function.Consumer;public class Button{public boolean active=true;public int x,y,w,h;public Component message;public Consumer<Button> action;public void setMessage(Component c){message=c;}public void click(){if(active)action.accept(this);}public static Builder builder(Component c,Consumer<Button> a){return new Builder(c,a);}public static class Builder{Button b=new Button();public Builder(Component c,Consumer<Button> a){b.message=c;b.action=a;}public Builder bounds(int x,int y,int w,int h){b.x=x;b.y=y;b.w=w;b.h=h;return this;}public Button build(){return b;}}}''')
write('net/minecraft/client/gui/components/EditBox.java','''package net.minecraft.client.gui.components;import net.minecraft.client.gui.Font;import net.minecraft.network.chat.Component;import java.util.function.Consumer;public class EditBox{public int x,y,w,h;String value="";Consumer<String> responder=s->{};public EditBox(Font f,int x,int y,int w,int h,Component c){this.x=x;this.y=y;this.w=w;this.h=h;}public void setMaxLength(int n){}public void setResponder(Consumer<String> c){responder=c;}public void setValue(String s){value=s;responder.accept(s);}public String getValue(){return value;}}''')
write('pl/aridlin/psychiatrykroles/peeb/PeebPackets.java','''package pl.aridlin.psychiatrykroles.peeb;public class PeebPackets{public static PeebConfig.Values saved;public static int requests,reloads;public static void requestConfig(){requests++;}public static void saveConfig(PeebConfig.Values v){saved=v;}public static void reloadConfig(){reloads++;}}''')
write('pl/aridlin/psychiatrykroles/peeb/client/PeebAdminGuiTest.java','''package pl.aridlin.psychiatrykroles.peeb.client;
import java.util.*;import net.minecraft.client.Minecraft;import net.minecraft.client.gui.screens.Screen;import net.minecraft.network.chat.Component;import net.minecraft.client.gui.components.*;import pl.aridlin.psychiatrykroles.peeb.*;
public final class PeebAdminGuiTest{
 static int checks;static void check(boolean v,String s){checks++;if(!v)throw new AssertionError(s);}static Button button(PeebSettingsScreen s,String prefix){return s.widgets.stream().filter(v->v instanceof Button).map(v->(Button)v).filter(v->v.message.text().startsWith(prefix)).findFirst().orElseThrow();}
 public static void main(String[] args){
  Minecraft m=Minecraft.getInstance();Screen back=new Screen(Component.literal("admin"));m.setScreen(back);PeebSettingsScreen.request(back);check(PeebPackets.requests==1,"requests server values");
  var settings=new PeebConfig.Values(8,.4,.8,.3,false,1.23456789);PeebSettingsScreen.receive(settings);check(m.screen instanceof PeebSettingsScreen,"server values open screen");var s=(PeebSettingsScreen)m.screen;
  var sliders=s.widgets.stream().filter(v->v instanceof AbstractSliderButton).map(v->(AbstractSliderButton)v).toList();check(sliders.size()==5,"five controls");var stop=sliders.get(4);check(stop.message.text().startsWith("Pull stop distance (blocks)"),"stop label");check(Math.abs(stop.normalized()-settings.stopDistance()/32)<1E-12,"configured slider");
  EditBox input=(EditBox)s.widgets.stream().filter(v->v instanceof EditBox).findFirst().orElseThrow();check(Double.parseDouble(input.getValue())==settings.stopDistance(),"exact existing value shown");check(input.x>=stop.x+stop.w,"input does not overlap slider");Button apply=button(s,"Apply");check(apply.y>input.y+input.h,"no new row overlap");
  apply.click();check(PeebPackets.saved.equals(settings),"unchanged save preserves precision and all fields");button(s,"Fall damage").click();apply.click();check(PeebPackets.saved.fallImmunity()&&PeebPackets.saved.stopDistance()==settings.stopDistance(),"other field preserves stop distance");
  input.setValue("2.25");check(apply.active&&Math.abs(stop.normalized()-2.25/32)<1E-12,"numeric input syncs slider");apply.click();check(PeebPackets.saved.stopDistance()==2.25,"numeric value sent");
  for(String invalid:new String[]{"","garbage","NaN","Infinity","-0.01","32.01"}){var previous=PeebPackets.saved;input.setValue(invalid);check(!apply.active,"invalid disables apply");apply.click();check(PeebPackets.saved==previous,"invalid input cannot silently overwrite");}
  input.setValue("0");check(apply.active&&stop.normalized()==0,"zero supported");apply.click();check(PeebPackets.saved.stopDistance()==0,"full pull value sent");
  stop.testSet(.5);check(input.getValue().equals("16.0")&&apply.active,"slider syncs numeric field");apply.click();check(PeebPackets.saved.stopDistance()==16,"slider value sent");stop.testSet(1);apply.click();check(PeebPackets.saved.stopDistance()==32,"upper bound");
  button(s,"Reload").click();check(PeebPackets.reloads==1,"reload command retained");PeebSettingsScreen.receive(new PeebConfig.Values(6,.2,.3,.4,false,.125));check(m.screen==s,"server update preserves screen");button(s,"Apply").click();check(PeebPackets.saved.stopDistance()==.125&&PeebPackets.saved.range()==6,"server update includes distance");
  button(s,"Defaults").click();button(s,"Apply").click();check(PeebPackets.saved.equals(PeebConfig.DEFAULT),"defaults explicitly zero");button(s,"Back").click();check(m.screen==back,"back retained");
  for(double v:new double[]{0,.001,2.5,32})check(PeebSettingsScreen.parseStopDistance(Double.toString(v))==v,"exact parser bound");
  System.out.println("{\\"success\\":true,\\"checks\\":"+checks+",\\"game_launched\\":false}");
 }
}''')
screen=R/'src/pl/aridlin/psychiatrykroles/peeb/client/PeebSettingsScreen.java';cp=str(R/'build/classes')+':'+(R/'build/classpath.txt').read_text().strip()
x=subprocess.run(['nice','-n','19','javac','--release','21','-proc:none','-cp',cp,'-d',str(C),*map(str,sorted(S.rglob('*.java'))),str(screen)],text=True,capture_output=True);(B/'compile.log').write_text(x.stdout+x.stderr)
if x.returncode:raise RuntimeError(x.stderr)
x=subprocess.run(['nice','-n','19','java','-Xmx128m','-cp',str(C)+':'+cp,'pl.aridlin.psychiatrykroles.peeb.client.PeebAdminGuiTest'],text=True,capture_output=True);(B/'test.log').write_text(x.stdout+x.stderr)
if x.returncode:raise RuntimeError(x.stderr)
proof=json.loads(x.stdout[x.stdout.rfind('{'):]);proof['scope']='Actual authored PeebSettingsScreen with headless UI/transport doubles and compiled actual Values';proof['source_sha256']=hashlib.sha256(screen.read_bytes()).hexdigest();(R/'build/gui-test.json').write_text(json.dumps(proof,indent=2)+'\n');print(json.dumps(proof))
