package pl.aridlin.kukirin;
import net.minecraft.client.Minecraft;
import net.minecraft.client.resources.sounds.AbstractTickableSoundInstance;
import net.minecraft.sounds.SoundSource;
import net.minecraft.util.Mth;
import net.neoforged.api.distmarker.Dist;
import net.neoforged.bus.api.SubscribeEvent;
import net.neoforged.fml.common.EventBusSubscriber;
import net.neoforged.neoforge.client.event.ClientTickEvent;
import net.neoforged.neoforge.client.event.ViewportEvent;
@EventBusSubscriber(modid="goplanska_kukirin",value=Dist.CLIENT)
public final class ScooterClient {
 private static int hintRider=-1,hintTicks;
 private static float previousSpeed,speed,previousRoll,roll,previousLungeKick,lungeKick;private static int lungeRider=-1,seenLunge;private static boolean jump,forwardDown;private static long lastForwardTap;
 private static final java.util.Map<Integer,Motor> motors=new java.util.HashMap<>();private static Wind wind;private static final java.util.Map<Integer,TyreScrub> scrubs=new java.util.HashMap<>();private static final java.util.Map<Integer,Nitro> nitros=new java.util.HashMap<>();private static int controlled=-1;private static boolean sentMouse;
 @SubscribeEvent public static void settings(net.neoforged.neoforge.client.event.RegisterClientCommandsEvent e){e.getDispatcher().register(net.minecraft.commands.Commands.literal("scooterhelp").executes(c->{Minecraft.getInstance().execute(()->Minecraft.getInstance().setScreen(new ScooterGuideScreen(()->Minecraft.getInstance().setScreen(null))));return 1;}));e.getDispatcher().register(net.minecraft.commands.Commands.literal("scootersettings").executes(c->{Minecraft.getInstance().execute(()->Minecraft.getInstance().setScreen(new ScooterSettingsScreen()));return 1;}));}
 @SubscribeEvent public static void forwardTap(net.neoforged.neoforge.client.event.InputEvent.Key event){var mc=Minecraft.getInstance();if(event.getAction()!=org.lwjgl.glfw.GLFW.GLFW_PRESS||mc.screen!=null||mc.player==null||!(mc.player.getVehicle() instanceof Scooter)||!mc.options.keyUp.matches(event.getKey(),event.getScanCode()))return;long now=System.nanoTime();if(lastForwardTap!=0&&now-lastForwardTap<350_000_000L){net.neoforged.neoforge.network.PacketDistributor.sendToServer(new ScooterLunge());lastForwardTap=0;}else lastForwardTap=now;}
 @SubscribeEvent public static void rocketBlockUse(net.neoforged.neoforge.event.entity.player.PlayerInteractEvent.RightClickBlock e){if(e.getLevel().isClientSide&&e.getEntity().getVehicle() instanceof Scooter s&&!ScooterRental.isRental(s)&&e.getItemStack().is(net.minecraft.world.item.Items.FIREWORK_ROCKET)){net.neoforged.neoforge.network.PacketDistributor.sendToServer(new ScooterRocket(e.getHand()==net.minecraft.world.InteractionHand.OFF_HAND));e.setCancellationResult(net.minecraft.world.InteractionResult.SUCCESS);e.setCanceled(true);}}
 @SubscribeEvent public static void rocketUse(net.neoforged.neoforge.event.entity.player.PlayerInteractEvent.RightClickItem e){if(e.getLevel().isClientSide&&e.getEntity().getVehicle() instanceof Scooter s&&!ScooterRental.isRental(s)&&e.getItemStack().is(net.minecraft.world.item.Items.FIREWORK_ROCKET)){net.neoforged.neoforge.network.PacketDistributor.sendToServer(new ScooterRocket(e.getHand()==net.minecraft.world.InteractionHand.OFF_HAND));e.setCancellationResult(net.minecraft.world.InteractionResult.SUCCESS);e.setCanceled(true);}}
 @SubscribeEvent public static void tick(ClientTickEvent.Post e){
  var mc=Minecraft.getInstance();var options=ScooterClientOptions.get();previousSpeed=speed;previousRoll=roll;if(net.neoforged.fml.ModList.get().isLoaded("lambdynlights_runtime"))ScooterHeadlights.tick();
  Scooter rider=mc.player!=null&&mc.player.getVehicle() instanceof Scooter s?s:null;
  if(rider==null){hintRider=-1;hintTicks=0;}else if(hintRider!=rider.getId()){hintRider=rider.getId();hintTicks=100;}else if(hintTicks>0)hintTicks--;
  previousLungeKick=lungeKick;lungeKick*=.80f;if(rider==null||!options.effectsEnabled){lungeKick=0;lungeRider=-1;}else if(lungeRider!=rider.getId()){lungeRider=rider.getId();seenLunge=rider.lungeSerial();}else if(seenLunge!=rider.lungeSerial()){seenLunge=rider.lungeSerial();lungeKick=8f;}
  if(rider!=null&&rider.getControllingPassenger()==mc.player&&(controlled!=rider.getId()||sentMouse!=options.mouseSteering||mc.player.tickCount%4==0)){net.neoforged.neoforge.network.PacketDistributor.sendToServer(new ScooterControl(options.mouseSteering,rider.steering(1),mc.options.keyJump.isDown(),mc.screen==null&&mc.options.keySprint.isDown()));rider.easyDrift(mc.screen==null&&mc.options.keySprint.isDown());rider.mouseSteering(options.mouseSteering);rider.thrustUp(mc.options.keyJump.isDown());controlled=rider.getId();sentMouse=options.mouseSteering;}if(rider==null){controlled=-1;lastForwardTap=0;}
  boolean down=mc.options.keyJump.isDown();if(down&&!jump&&rider!=null&&!rider.rocketActive()&&mc.screen==null)net.neoforged.neoforge.network.PacketDistributor.sendToServer(new ScooterBoost());jump=down;
  float target=rider==null||!options.effectsEnabled?0:Math.min(1,rider.speed(1)/(float)ScooterHandling.TOP_SPEED);
  speed=Mth.lerp(.15f,speed,target);roll=Mth.lerp(.15f,roll,rider==null||!options.effectsEnabled?0:-rider.steering(1)/28*target*options.cameraLeanDegrees*(1+.65f*rider.driftEffect()));
  scrubs.entrySet().removeIf(entry->entry.getValue().isStopped());if(mc.level!=null&&mc.player!=null&&options.audioEnabled)for(var entity:mc.level.entitiesForRendering())if(entity instanceof Scooter s&&s.driftEffect()>.12f&&s.distanceToSqr(mc.player)<32*32&&!scrubs.containsKey(s.getId())){var sound=new TyreScrub(s);scrubs.put(s.getId(),sound);mc.getSoundManager().play(sound);}
  nitros.entrySet().removeIf(entry->entry.getValue().isStopped());
  if(mc.level!=null&&mc.player!=null&&options.audioEnabled)for(var entity:mc.level.entitiesForRendering())if(entity instanceof Scooter s&&s.rocketActive()&&s.distanceToSqr(mc.player)<48*48&&!nitros.containsKey(s.getId())){var sound=new Nitro(s);nitros.put(s.getId(),sound);mc.getSoundManager().play(sound);}
  motors.entrySet().removeIf(entry->entry.getValue().isStopped()||(mc.level!=null&&mc.level.getGameTime()-entry.getValue().created>10&&!mc.getSoundManager().isActive(entry.getValue())));
  if(mc.level!=null&&mc.player!=null&&options.audioEnabled&&mc.options.getSoundSourceVolume(SoundSource.MASTER)>0){for(var entity:mc.level.entitiesForRendering())if(entity instanceof Scooter s&&s.isVehicle()&&s.distanceToSqr(mc.player)<32*32&&!motors.containsKey(s.getId())){var motor=new Motor(s);motors.put(s.getId(),motor);mc.getSoundManager().play(motor);}}
  if(rider!=null&&options.audioEnabled&&(wind==null||wind.isStopped()||(mc.level.getGameTime()-wind.created>10&&!mc.getSoundManager().isActive(wind)))){wind=new Wind(rider);mc.getSoundManager().play(wind);}
 }
 private record RiderHead(float head,float oldHead){}
 private static final java.util.Map<java.util.UUID,RiderHead> riderHeads=new java.util.HashMap<>();
 @SubscribeEvent(priority=net.neoforged.bus.api.EventPriority.LOWEST) public static void playerStep(net.neoforged.neoforge.client.event.RenderPlayerEvent.Pre e){if(!e.isCanceled()&&e.getEntity().getVehicle() instanceof Scooter s){var p=e.getEntity();riderHeads.put(p.getUUID(),new RiderHead(p.yHeadRot,p.yHeadRotO));p.yHeadRot=s.getYRot();p.yHeadRotO=s.yRotO;s.yBodyRot=s.getYRot();s.yBodyRotO=s.yRotO;e.getPoseStack().pushPose();e.getPoseStack().translate(0,s.suspension(e.getPartialTick())+s.stepOffset(e.getPartialTick()),0);}}
 @SubscribeEvent public static void playerStepEnd(net.neoforged.neoforge.client.event.RenderPlayerEvent.Post e){if(e.getEntity().getVehicle() instanceof Scooter){var saved=riderHeads.remove(e.getEntity().getUUID());if(saved!=null){e.getEntity().yHeadRot=saved.head();e.getEntity().yHeadRotO=saved.oldHead();}e.getPoseStack().popPose();}}
 @SubscribeEvent public static void hideVehicleHearts(net.neoforged.neoforge.client.event.RenderGuiLayerEvent.Pre e){var p=Minecraft.getInstance().player;if(p!=null&&p.getVehicle() instanceof Scooter&&e.getName().equals(net.neoforged.neoforge.client.gui.VanillaGuiLayers.VEHICLE_HEALTH))e.setCanceled(true);}
 @SubscribeEvent public static void hud(net.neoforged.neoforge.client.event.RenderGuiEvent.Post e){var mc=Minecraft.getInstance();if(mc.player==null||!(mc.player.getVehicle() instanceof Scooter s)||mc.options.hideGui)return;boolean speed=ScooterClientOptions.get().speedometerEnabled;if(speed||ScooterRental.isRental(s))ScooterDial.draw(e.getGuiGraphics(),mc.font,s,speed);}

 @SubscribeEvent public static void ridingHint(net.neoforged.neoforge.client.event.RenderGuiEvent.Post e){var mc=Minecraft.getInstance();if(hintTicks<=0||mc.player==null||!(mc.player.getVehicle() instanceof Scooter)||mc.options.hideGui)return;var text=net.minecraft.network.chat.Component.translatable("scooter.hud.controls",mc.options.keyInventory.getTranslatedKeyMessage(),mc.options.keyShift.getTranslatedKeyMessage());int width=mc.font.width(text),x=(e.getGuiGraphics().guiWidth()-width)/2,y=e.getGuiGraphics().guiHeight()-65;e.getGuiGraphics().fill(x-4,y-3,x+width+4,y+12,0x990b1016);e.getGuiGraphics().drawString(mc.font,text,x,y,0xffeeeeee);}
 @SubscribeEvent public static void fov(ViewportEvent.ComputeFov e){if(e.usedConfiguredFov()){var mc=Minecraft.getInstance();e.setFOV(e.getFOV()+Mth.lerp((float)e.getPartialTick(),previousSpeed,speed)*ScooterClientOptions.get().fovBoostDegrees*mc.options.fovEffectScale().get()+Mth.lerp((float)e.getPartialTick(),previousLungeKick,lungeKick)*mc.options.fovEffectScale().get());}}
 @SubscribeEvent public static void camera(ViewportEvent.ComputeCameraAngles e){var mc=Minecraft.getInstance();if(mc.options.getCameraType().isFirstPerson())e.setRoll(e.getRoll()+Mth.lerp((float)e.getPartialTick(),previousRoll,roll));}
 private static boolean alive(Scooter s){var mc=Minecraft.getInstance();return mc.level==s.level()&&!s.isRemoved()&&s.isVehicle()&&mc.player!=null&&s.distanceToSqr(mc.player)<40*40&&ScooterClientOptions.get().audioEnabled;}
 static final class Motor extends AbstractTickableSoundInstance {
  final Scooter scooter;final long created;float lastMotionSpeed,load;Motor(Scooter s){super(Kukirin.MOTOR.get(),SoundSource.NEUTRAL,net.minecraft.util.RandomSource.create());scooter=s;created=s.level().getGameTime();looping=true;delay=0;volume=.01f;}
  @Override public void tick(){if(!alive(scooter)){stop();return;}float current=(float)(scooter.isControlledByLocalInstance()?scooter.getDeltaMovement().horizontalDistance():scooter.speed(1));float acceleration=Math.clamp((current-lastMotionSpeed)/.027f,-1,1);lastMotionSpeed=current;load=Mth.lerp(.22f,load,acceleration);float speed=Math.clamp(current/(float)ScooterHandling.TOP_SPEED,0,1.25f),positive=Math.max(0,load),negative=Math.max(0,-load);pitch=Mth.lerp(.18f,pitch,.65f+.55f*speed+.65f*positive-.22f*negative);volume=Mth.lerp(.18f,volume,ScooterClientOptions.get().motorVolume*Math.clamp(.06f+.30f*speed+.60f*positive-.15f*negative,.02f,1));x=scooter.getX();y=scooter.getY();z=scooter.getZ();}
 }
 static final class Nitro extends AbstractTickableSoundInstance {
 final Scooter scooter;Nitro(Scooter s){super(Kukirin.NITRO.get(),SoundSource.NEUTRAL,net.minecraft.util.RandomSource.create());scooter=s;looping=true;delay=0;volume=.6f;pitch=1;}
 @Override public void tick(){if(!alive(scooter)||!scooter.rocketActive()){stop();return;}x=scooter.getX();y=scooter.getY();z=scooter.getZ();volume=ScooterClientOptions.get().motorVolume*.85f;pitch=.8f+Math.min(1,scooter.speed(1)/2.8f)*.5f;}
 }
 static final class TyreScrub extends AbstractTickableSoundInstance {
  final Scooter scooter;int quiet;TyreScrub(Scooter s){super(Kukirin.DRIFT.get(),SoundSource.NEUTRAL,net.minecraft.util.RandomSource.create());scooter=s;looping=true;delay=0;volume=.02f;}
  @Override public void tick(){if(!alive(scooter)){stop();return;}float slip=scooter.driftEffect();if(slip<.025f){if(++quiet>10){stop();return;}}else quiet=0;volume=Mth.lerp(.2f,volume,ScooterClientOptions.get().motorVolume*.8f*slip);pitch=.8f+Math.min(1,scooter.speed(1)/(float)ScooterHandling.TOP_SPEED)*.45f;x=scooter.getX();y=scooter.getY()+.15;z=scooter.getZ();}
 }
 static final class Wind extends AbstractTickableSoundInstance {
  final Scooter scooter;final long created;Wind(Scooter s){super(Kukirin.WIND.get(),SoundSource.PLAYERS,net.minecraft.util.RandomSource.create());scooter=s;created=s.level().getGameTime();looping=true;relative=true;attenuation=Attenuation.NONE;volume=.001f;}
  @Override public void tick(){var mc=Minecraft.getInstance();if(!alive(scooter)||mc.player.getVehicle()!=scooter){stop();return;}float speed=Math.min(1,scooter.speed(1)/(float)ScooterHandling.TOP_SPEED);volume=Mth.lerp(.1f,volume,ScooterClientOptions.get().windVolume*speed*speed);pitch=.8f+speed*.4f;}
 }
}
