package pl.aridlin.psychiatrykroles;

import com.google.gson.JsonObject;
import com.google.gson.JsonParser;
import net.minecraft.core.BlockPos;

import java.io.IOException;
import java.nio.ByteBuffer;
import java.nio.channels.FileChannel;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardOpenOption;

/** A completed copy of the archived world is required before any legacy chunk is loaded. */
final class OldWorldImport {
    static final String DIRECTORY = "dimensions/psychiatryk_roles/old_overworld";
    static final String READY_FILE = "psychiatryk-import-ready.json";
    private static final int SECTOR_BYTES = 4096;

    record Manifest(int sourceDataVersion, BlockPos spawn) {}

    private OldWorldImport() {}

    static Manifest readManifest(Path directory) throws IOException {
        Path path = directory.resolve(READY_FILE);
        if (!Files.isRegularFile(path) || Files.size(path) > 4096) {
            throw new IOException("Legacy world import is not marked ready");
        }
        try {
            JsonObject json = JsonParser.parseString(Files.readString(path)).getAsJsonObject();
            if (json.get("version").getAsInt() != 1) throw new IllegalArgumentException("Unsupported marker version");
            int dataVersion = json.get("sourceDataVersion").getAsInt();
            JsonObject spawn = json.getAsJsonObject("spawn");
            BlockPos pos = new BlockPos(spawn.get("x").getAsInt(), spawn.get("y").getAsInt(),
                spawn.get("z").getAsInt());
            if (dataVersion <= 0 || Math.abs((long) pos.getX()) > 29_999_984L
                || Math.abs((long) pos.getZ()) > 29_999_984L || pos.getY() < -64 || pos.getY() >= 320) {
                throw new IllegalArgumentException("Invalid source version or spawn position");
            }
            return new Manifest(dataVersion, pos);
        } catch (RuntimeException error) {
            throw new IOException("Invalid legacy-world import marker", error);
        }
    }

    /** Read the Anvil location table directly; a missing chunk must never be generated by this command. */
    static boolean hasImportedChunk(Path directory, int blockX, int blockZ) {
        int chunkX = Math.floorDiv(blockX, 16);
        int chunkZ = Math.floorDiv(blockZ, 16);
        int regionX = Math.floorDiv(chunkX, 32);
        int regionZ = Math.floorDiv(chunkZ, 32);
        Path region = directory.resolve("region/r." + regionX + "." + regionZ + ".mca");
        int localX = Math.floorMod(chunkX, 32);
        int localZ = Math.floorMod(chunkZ, 32);
        long headerOffset = 4L * (localX + 32 * localZ);
        try (FileChannel channel = FileChannel.open(region, StandardOpenOption.READ)) {
            long size = channel.size();
            if (size < 2L * SECTOR_BYTES) return false;
            ByteBuffer entry = ByteBuffer.allocate(4);
            if (channel.read(entry, headerOffset) != 4) return false;
            entry.flip();
            int sectorOffset = (Byte.toUnsignedInt(entry.get()) << 16)
                | (Byte.toUnsignedInt(entry.get()) << 8) | Byte.toUnsignedInt(entry.get());
            int sectors = Byte.toUnsignedInt(entry.get());
            return sectorOffset >= 2 && sectors > 0
                && (sectorOffset + (long) sectors) * SECTOR_BYTES <= size;
        } catch (IOException error) {
            return false;
        }
    }
}
